behaviors:
  TrafficCar:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 2000000
    summary_freq: 10000
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.99
      learning_rate: 3.0e-4
      beta: 5.0e-4
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        gamma: 0.99
        strength: 0.01
        demo_path: Demos/CarAgentDemo.demo
    behavioral_cloning:
      strength: 1.0
      demo_path: Demos/CarAgentDemo.demo
      steps: 200000